# 本願環境のDBに対してマイグレーションを実行する。 mainマージ時に実行する
# TODO: 現在このworkflowは動かない。マイグレーションはCLI上で行うこと
# バグについてissue報告済 https://github.com/cloudflare/workers-sdk/issues/3598

name: Migrate Database Prod to Cloudflare D1
on:
  push:
    paths:
      - 'packages/db/migrations/**'
      - '.github/workflows/migrate-db-prod.workflow.yml'
    branches:
      # - main
      - stop # 返答やアップデートがあれば、発火ブランチをmainに修正する。
  workflow_dispatch:

jobs:
  deploy:
    name: Migrate D1 Database with Wrangler (Prod)
    runs-on: ubuntu-latest
    env:
      NO_D1_WARNING: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.2
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Run Migration
        run: pnpm run migrate:apply-prod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        working-directory: ./packages/db
